[theme]
base = "light"
primaryColor = "#3a3a3a"             # Grafite elegante para botões e links
backgroundColor = "#f7f9fb"          # Branco frio e limpo (fundo geral)
secondaryBackgroundColor = "#e6ecf1" # Painéis discretos, com ar institucional
textColor = "#1d1d1f"                # Quase preto, leitura perfeita em telas

[theme.sidebar]
backgroundColor = "#cfd8e3"          # Cinza-azulado leve e sofisticado
textColor = "#2a2a2e"                # Escuro neutro, leitura clara sem contraste forte
