[theme]
base = "light"
primaryColor = "#5c5c5c"             # Cinza escuro elegante para interações (botões, links)
backgroundColor = "#f4f4f4"          # Branco suave para fundo geral
secondaryBackgroundColor = "#e0e0e0" # Painéis/cards com contraste sutil
textColor = "#1a1a1a"                # Quase preto, excelente legibilidade

[theme.sidebar]
backgroundColor = "#d6d6d6"          # Cinza claro sofisticado na sidebar
textColor = "#2b2b2b" 
